
INSERT INTO `waz_quartier` (`quartier_libelle`,`quartier_commune_id`) VALUES ("amet ornare lectus",9),("et ipsum cursus",79),("luctus sit amet,",7),("sed dolor. Fusce",92),("neque. Nullam nisl.",57),("nonummy. Fusce fermentum",54),("odio. Phasellus at",91),("a tortor. Nunc",7),("Quisque varius. Nam",89),("interdum. Curabitur dictum.",32);
INSERT INTO `waz_quartier` (`quartier_libelle`,`quartier_commune_id`) VALUES ("Etiam gravida molestie",13),("eleifend. Cras sed",71),("semper cursus. Integer",72),("pede. Suspendisse dui.",34),("sem magna nec",33),("malesuada id, erat.",69),("augue. Sed molestie.",12),("lorem, sit amet",7),("mattis. Integer eu",52),("dapibus id, blandit",34);
INSERT INTO `waz_quartier` (`quartier_libelle`,`quartier_commune_id`) VALUES ("lorem fringilla ornare",63),("tempus mauris erat",52),("Curabitur vel lectus.",97),("vulputate ullamcorper magna.",31),("sit amet ante.",47),("taciti sociosqu ad",40),("egestas. Aliquam fringilla",52),("magna. Nam ligula",64),("metus urna convallis",44),("blandit enim consequat",26);
INSERT INTO `waz_quartier` (`quartier_libelle`,`quartier_commune_id`) VALUES ("non leo. Vivamus",24),("Nulla interdum. Curabitur",18),("posuere cubilia Curae;",68),("mauris. Suspendisse aliquet",16),("erat, in consectetuer",11),("velit egestas lacinia.",74),("varius. Nam porttitor",70),("diam at pretium",12),("egestas hendrerit neque.",65),("risus a ultricies",50);
INSERT INTO `waz_quartier` (`quartier_libelle`,`quartier_commune_id`) VALUES ("tincidunt vehicula risus.",65),("nec, mollis vitae,",79),("felis. Donec tempor,",11),("orci quis lectus.",19),("et tristique pellentesque,",73),("placerat velit. Quisque",18),("tempor augue ac",71),("bibendum. Donec felis",34),("velit eget laoreet",68),("natoque penatibus et",77);
INSERT INTO `waz_quartier` (`quartier_libelle`,`quartier_commune_id`) VALUES ("ornare egestas ligula.",71),("aliquet lobortis, nisi",80),("dis parturient montes,",99),("neque. Morbi quis",30),("Nullam enim. Sed",68),("Proin vel arcu",64),("mattis ornare, lectus",41),("montes, nascetur ridiculus",56),("hendrerit a, arcu.",68),("ipsum sodales purus,",75);
INSERT INTO `waz_quartier` (`quartier_libelle`,`quartier_commune_id`) VALUES ("Nulla tempor augue",50),("vulputate, posuere vulputate,",34),("luctus vulputate, nisi",71),("lorem. Donec elementum,",74),("Duis dignissim tempor",36),("aliquet diam. Sed",78),("neque venenatis lacus.",91),("dignissim magna a",65),("accumsan sed, facilisis",86),("sed, sapien. Nunc",69);
INSERT INTO `waz_quartier` (`quartier_libelle`,`quartier_commune_id`) VALUES ("tellus justo sit",14),("sodales nisi magna",16),("ridiculus mus. Donec",18),("Etiam bibendum fermentum",70),("eros nec tellus.",25),("non lorem vitae",46),("dictum sapien. Aenean",88),("vel arcu eu",76),("ipsum ac mi",48),("Donec consectetuer mauris",20);
INSERT INTO `waz_quartier` (`quartier_libelle`,`quartier_commune_id`) VALUES ("Integer vitae nibh.",86),("egestas. Fusce aliquet",10),("enim non nisi.",28),("euismod mauris eu",7),("nisl. Quisque fringilla",18),("commodo ipsum. Suspendisse",8),("egestas hendrerit neque.",85),("tellus, imperdiet non,",94),("non, bibendum sed,",23),("diam lorem, auctor",9);
INSERT INTO `waz_quartier` (`quartier_libelle`,`quartier_commune_id`) VALUES ("sem magna nec",35),("leo. Cras vehicula",3),("Nunc quis arcu",9),("vulputate dui, nec",47),("et tristique pellentesque,",53),("pede sagittis augue,",65),("mi lacinia mattis.",65),("tincidunt. Donec vitae",39),("lacus pede sagittis",77),("ornare, elit elit",28);
