
INSERT INTO `waz_photos` (`photo_libelle`,`photo_log_id`) VALUES ("snxrkorgwszi.jpg",76),("ofidegdrkzcg.jpg",18),("edpqsfjsalxr.jpg",39),("idtowqyxygar.jpg",32),("nglafmpbjvzc.jpg",32),("yvmcmkvntkkj.jpg",67),("zkgfzoxlzyja.jpg",73),("rkrsqkajgaxq.jpg",70),("pkxucnllbsxj.jpg",2),("ijnlilwvkjbg.jpg",50);
INSERT INTO `waz_photos` (`photo_libelle`,`photo_log_id`) VALUES ("dmcsgqfemyrs.jpg",35),("ydokxcccksfx.jpg",49),("mwrwcadqixxi.jpg",82),("ncmbcgrfxdor.jpg",44),("sulimqxwvano.jpg",28),("xeppyuuqrdtu.jpg",28),("lcrhjijdridv.jpg",35),("ewlykgwsvsuw.jpg",65),("vlpehoxmlbxf.jpg",67),("sdxsfjovtfpr.jpg",92);
INSERT INTO `waz_photos` (`photo_libelle`,`photo_log_id`) VALUES ("pjitcsdbsfpe.jpg",51),("hntdnswdtrpt.jpg",55),("rbcdthaqyvvh.jpg",43),("bkxrippjcstv.jpg",15),("xhrvguabdopo.jpg",52),("ghxziugnjxug.jpg",14),("yfriqgtoigzx.jpg",87),("syxycohxaprh.jpg",44),("gtgtcatygjnn.jpg",99),("qvkkhxnlyhkv.jpg",68);
INSERT INTO `waz_photos` (`photo_libelle`,`photo_log_id`) VALUES ("pzzerhhwggzb.jpg",54),("vbdjuvkkjagb.jpg",79),("hsqvoqyxrckb.jpg",80),("oolmuutduare.jpg",28),("oquzebertztt.jpg",7),("vxelsgkypiex.jpg",76),("itrxqzoetzpf.jpg",57),("nfbheovkacwj.jpg",93),("wioxxtjlgwoz.jpg",97),("amisypuxkoig.jpg",96);
INSERT INTO `waz_photos` (`photo_libelle`,`photo_log_id`) VALUES ("azbdjfgktvww.jpg",25),("toaogozeykoo.jpg",85),("oxoltfdawwlo.jpg",43),("vheagkztuibe.jpg",57),("vpwhibyoswwu.jpg",33),("wnulffhtxhcw.jpg",50),("yzqrrhmswrkr.jpg",22),("awwsbbjdopga.jpg",42),("pzcilmkbqpwk.jpg",22),("fqbabripbjrq.jpg",95);
INSERT INTO `waz_photos` (`photo_libelle`,`photo_log_id`) VALUES ("yhsykohpkrox.jpg",63),("uorkyawjszhd.jpg",49),("jbwfsikgqego.jpg",43),("bddtpcxttdfi.jpg",38),("rgskiyuwvuxu.jpg",75),("vayxazhrqwcl.jpg",67),("jedbinhprkdc.jpg",90),("irbjfkssqcvn.jpg",73),("vmcuqvyibqah.jpg",9),("hrhhicmmxyco.jpg",55);
INSERT INTO `waz_photos` (`photo_libelle`,`photo_log_id`) VALUES ("sjcwfnpmzbnm.jpg",20),("eocwtbyzfmnn.jpg",23),("nhhjgjhbtlfe.jpg",28),("koqmletedhpx.jpg",10),("aexbviftszfs.jpg",94),("ixwraebqsjfl.jpg",70),("dsiqzqljhlyh.jpg",81),("plksxyhnzcpf.jpg",11),("hivwiuleoczl.jpg",17),("owhxfoayhrng.jpg",97);
INSERT INTO `waz_photos` (`photo_libelle`,`photo_log_id`) VALUES ("iksnuoifonxz.jpg",83),("krhwxuejrwih.jpg",93),("foveoeasoqtz.jpg",93),("bxljssvttbhh.jpg",19),("dovocjcdespl.jpg",96),("nslstqcaynhh.jpg",1),("pyhdotpclwrv.jpg",58),("zfqzxdhfpmvk.jpg",64),("lowbttnabghi.jpg",55),("xxockvbcgsfx.jpg",63);
INSERT INTO `waz_photos` (`photo_libelle`,`photo_log_id`) VALUES ("puzkapiixrkp.jpg",9),("zgggzslinipm.jpg",52),("kinafyqgcdwg.jpg",47),("sxgiruwhiipq.jpg",39),("otiqpjyqevwk.jpg",89),("qmtfgnhucfin.jpg",100),("zjhmsrgldmfb.jpg",81),("dargliuzajsg.jpg",36),("aqalvnjhfmtu.jpg",81),("knxjhskzkxeb.jpg",68);
INSERT INTO `waz_photos` (`photo_libelle`,`photo_log_id`) VALUES ("dzdgtxwgoetq.jpg",33),("kxbodvgfpwvk.jpg",97),("yerxvwsnflyc.jpg",39),("xebzgdgrlabr.jpg",40),("ospdwbgjllvz.jpg",52),("ettuwikdtoeo.jpg",65),("dakoivrdrcfm.jpg",77),("wduykwihgjop.jpg",21),("qxspupnhnwva.jpg",39),("zuvadzqxdrai.jpg",83);
